name: Trying to publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ci-publish
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: package-lock.json
        env:
          FORCE_COLOR: 0

      - name: Install dependencies
        run: npm ci

      - name: Patching
        id: patching
        run: npm start
        continue-on-error: true

      - name: Publish
        if: steps.patching.outcome == 'success'
        working-directory: sheetjs
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
